default: &default
  adapter: postgresql
  encoding: unicode
  DATABASE_URL: postgres://postgres:@localhost:5432/test
  REDIS_URL: redis://localhost:6379/0
  RAILS_ENV: test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  pool: 5
  variables:
    statement_timeout: 5000

development:
  <<: *default

test:
  <<: *default
  DATABASE_URL: postgres://postgres:@localhost:5432/test
  REDIS_URL: redis://localhost:6379/0
  RAILS_ENV: test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

production:
  <<: *default